sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t utituc/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true utituc/react-test npm test 

after_success:
  - docker build -t utituc/multi-client ./client
  - docker build -t utituc/multi-nginx ./nginx
  - docker build -t utituc/multi-server ./server
  - docker build -t utituc/multi-worker ./worker
  # Log in to docker hub CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # and now take those images and push them to docer hub
  - docker push utituc/multi-client
  - docker push utituc/multi-nginx
  - docker push utituc/multi-server
  - docker push utituc/multi-worker

# this would be the deploy-part for AWS:
# deploy:
#   provider: elasticbeanstalk
#   region: 'us-east-1'
#   app: 'multi-docker'
#   env: 'MultiDocker-env'
#   bucket_name: 'elasticbeanstalk-us-east-1-923445559289'
#   bucket_path: 'docker-multi'
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY